services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: movies-frontend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/movies
    container_name: movies-backend

  mongodb:
    image: mongo:7.0.16 # Updated to MongoDB version 7.0.16
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
